DirectoryPath: "public"
IgnoreDirectoryMissingTrailingSlash: True
IgnoreURLs:
  - "fonts.gstatic.com"
  - "github.com"
  - "linkedin.com"
  - "marketplace.visualstudio.com"
  - "www.microsoft.com"
  - "localhost"
  - "127.0.0.1"
  - "192.168.64.39"
  - "/livereload.js"