apiVersion: v1
kind: Namespace
metadata:
  name: hosted-llm-chatbot

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: coredns
  namespace: hosted-llm-chatbot
spec:
  replicas: 2
  selector:
    matchLabels:
      app: coredns
  template:
    metadata:
      labels:
        app: coredns
    spec:
      containers:
      - name: coredns
        image: rancher/mirrored-coredns-coredns:1.10.1

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: local-path-provisioner
  namespace: hosted-llm-chatbot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: local-path-provisioner
  template:
    metadata:
      labels:
        app: local-path-provisioner
    spec:
      containers:
      - name: local-path-provisioner
        image: rancher/local-path-provisioner:v0.0.24

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: klipper-helm
  namespace: hosted-llm-chatbot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: klipper-helm
  template:
    metadata:
      labels:
        app: klipper-helm
    spec:
      containers:
      - name: klipper-helm
        image: rancher/klipper-helm:v0.8.0-build20230510

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: klipper-lb
  namespace: hosted-llm-chatbot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: klipper-lb
  template:
    metadata:
      labels:
        app: klipper-lb
    spec:
      containers:
      - name: klipper-lb
        image: rancher/klipper-lb:0.4.4

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: traefik
  namespace: hosted-llm-chatbot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: traefik
  template:
    metadata:
      labels:
        app: traefik
    spec:
      containers:
      - name: traefik
        image: rancher/mirrored-library-traefik:2.9.10

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: metrics-server
  namespace: hosted-llm-chatbot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metrics-server
  template:
    metadata:
      labels:
        app: metrics-server
    spec:
      containers:
      - name: metrics-server
        image: rancher/mirrored-metrics-server:v0.6.3

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: hosted-llm-chatbot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:5.0.5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: hosted-llm-chatbot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
  namespace: hosted-llm-chatbot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
      - name: mongo
        image: docker.io/mongo:4.0.10

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: tensorflow
  namespace: hosted-llm-chatbot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tensorflow
  template:
    metadata:
      labels:
        app: tensorflow
    spec:
      containers:
      - name: tensorflow
        image: tensorflow/tensorflow:2.16.1

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: rocketchat
  namespace: hosted-llm-chatbot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rocketchat
  template:
    metadata:
      labels:
        app: rocketchat
    spec:
      containers:
      - name: rocketchat
        image: rocket.chat:6.7.0
