#!/usr/bin/env python3
"""Generate kernel view table comparing SME2-On vs SME2-Off kernels from xnntrace logs.

This script extracts kernels from xnntrace logs and generates a markdown table
showing which kernels are present in each configuration.
"""

import argparse
import csv
import sys
from pathlib import Path
from typing import Dict, Set


def load_kernels_from_csv(csv_path: Path) -> Set[str]:
    """Load kernel names from a CSV file generated by xnntrace_to_kernels.py."""
    kernels = set()
    if not csv_path.exists():
        return kernels
    with csv_path.open() as f:
        reader = csv.DictReader(f)
        for row in reader:
            kernel = row.get("kernel_name", "").strip()
            if kernel:
                kernels.add(kernel)
    return kernels


def load_kernels_from_xnntrace(xnntrace_path: Path) -> Set[str]:
    """Load kernel names directly from xnntrace log file."""
    import re

    kernels = set()
    if not xnntrace_path.exists():
        return kernels

    # Pattern: Using <category> microkernel 'xnn_...'
    pattern = re.compile(r"Using\s+\w+\s+microkernel\s+'([^']+)'", re.IGNORECASE)
    with xnntrace_path.open(encoding="utf-8", errors="ignore") as f:
        for line in f:
            match = pattern.search(line)
            if match:
                kernels.add(match.group(1).strip())
    return kernels


def determine_architecture(kernel_name: str) -> str:
    """Determine architecture from kernel name."""
    kernel_lower = kernel_name.lower()
    if "sme2" in kernel_lower or "neonsme2" in kernel_lower:
        return "SME2"
    elif "sme" in kernel_lower:
        return "SME"
    elif "neon" in kernel_lower or "aarch64" in kernel_lower:
        return "NEON"
    else:
        return "Other"


def generate_kernel_view_table(
    sme2_on_kernels: Set[str],
    sme2_off_kernels: Set[str],
    filter_op: str = None,
) -> str:
    """Generate markdown table comparing kernels."""
    all_kernels = sorted(sme2_on_kernels | sme2_off_kernels)

    # Filter by operation type if specified
    if filter_op:
        all_kernels = [
            k for k in all_kernels if filter_op.lower() in k.lower()
        ]

    if not all_kernels:
        return "No kernels found matching the filter criteria.\n"

    lines = []
    lines.append("| Kernel Name | SME2-On | SME2-Off | Architecture | Delegation |")
    lines.append("|-------------|----------|----------|-------------|------------|")

    for kernel in all_kernels:
        on_present = "✅ **Present**" if kernel in sme2_on_kernels else "❌ **Absent**"
        off_present = (
            "✅ **Present**" if kernel in sme2_off_kernels else "❌ **Absent**"
        )
        arch = determine_architecture(kernel)
        lines.append(
            f"| `{kernel}` | {on_present} | {off_present} | {arch} | XNNPACK Delegated |"
        )

    return "\n".join(lines) + "\n"


def main():
    parser = argparse.ArgumentParser(
        description="Generate kernel view table from xnntrace logs or CSV files"
    )
    parser.add_argument(
        "--sme2-on",
        required=True,
        help="Path to SME2-ON xnntrace log or CSV file",
    )
    parser.add_argument(
        "--sme2-off",
        required=True,
        help="Path to SME2-OFF xnntrace log or CSV file",
    )
    parser.add_argument(
        "--out",
        help="Output markdown file path (default: stdout)",
    )
    parser.add_argument(
        "--filter-op",
        help="Filter kernels by operation type (e.g., 'gemm', 'igemm', 'conv')",
    )
    parser.add_argument(
        "--title",
        default="Kernel view (XNNPACK Delegated):",
        help="Title for the kernel view section",
    )

    args = parser.parse_args()

    # Load kernels
    sme2_on_path = Path(args.sme2_on)
    sme2_off_path = Path(args.sme2_off)

    if sme2_on_path.suffix == ".csv":
        sme2_on_kernels = load_kernels_from_csv(sme2_on_path)
    else:
        sme2_on_kernels = load_kernels_from_xnntrace(sme2_on_path)

    if sme2_off_path.suffix == ".csv":
        sme2_off_kernels = load_kernels_from_csv(sme2_off_path)
    else:
        sme2_off_kernels = load_kernels_from_xnntrace(sme2_off_path)

    # Generate table
    table = generate_kernel_view_table(
        sme2_on_kernels, sme2_off_kernels, filter_op=args.filter_op
    )

    # Add title
    output = f"#### **{args.title}**\n\n{table}"

    # Write output
    if args.out:
        out_path = Path(args.out)
        out_path.parent.mkdir(parents=True, exist_ok=True)
        out_path.write_text(output)
        print(f"Wrote kernel view to {out_path}", file=sys.stderr)
    else:
        print(output)


if __name__ == "__main__":
    main()

