name: Check Code Quality

on:
  # run once a day at 6AM UTC
  schedule:
    - cron: '0 6 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  check_links:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.98.0'
          extended: true

      - name: Build
        run: hugo --minify

      - name: Install dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y python3
          pip install html5lib
          pip install linkchecker

      - name: Run W3C Link Checker
        run: |
          linkchecker --check-extern -F yaml -f linkchecker-output.yaml -r 2 .htmltest.yml
        continue-on-error: true

      - name: Upload Link Checker output
        uses: actions/upload-artifact@v3
        with:
          name: linkchecker-output
          path: linkchecker-output.yaml

      - name: Retain artifacts
        run: |
          mkdir -p .github/artifacts
          cp linkchecker-output.yaml .github/artifacts/linkchecker-output.yaml
        env:
          RETENTION_DAYS: 7

      - name: Cleanup
        run: rm -rf .github/artifacts

      - name: Scan for malware
        run: |
          tools/install-scan.sh
          clamscan -r -i public -l scanlog
      - name: Scan results
        uses: actions/upload-artifact@v3
        with:
          name: clamscan-log
          path: scanlog
          retention-days: 7 # Default is 90 days

      - name: Spell check
        uses: rojopolis/spellcheck-github-actions@0.30.0
        with:
          config_path: .spellcheck.yml
          task_name: Markdown
          output_file: spellcheck-output.txt

      - name: Spelling results
        uses: actions/upload-artifact@v3
        with:
          name: spellcheck-output
          path: spellcheck-output.txt
          retention-days: 7 # Default
