name: Check Code Quality

on:
  # run once a day at 6AM UTC
  schedule:
    - cron: '0 6 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  check_links:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.98.0'
          extended: true

      - name: Build
        run: hugo --minify

      - name: Download and install W3C LinkChecker
        run: |
          wget https://cpan.metacpan.org/authors/id/D/DH/DHM/W3C-LinkChecker-5.0.0.tar.gz
          tar -xzf W3C-LinkChecker-5.0.0.tar.gz
          cd W3C-LinkChecker-5.0.0

          # Install cpanm (CPAN Minus)
          curl -LO https://cpanmin.us
          perl cpanmin.us --self-upgrade --no-wget App::cpanminus

          # Configure local::lib
          eval "$(perl -I$HOME/perl5/lib/perl5 -Mlocal::lib)"

          # Install the required modules using cpanm
          cpanm CSS::DOM CSS::DOM::Constants CSS::DOM::Style CSS::DOM::Util Config::General HTTP::Cookies LWP::RobotUA LWP::UserAgent Locale::Country Locale::Language Net::HTTP::Methods Net::IP

          # Build and install the W3C LinkChecker module
          perl Makefile.PL
          make
          make test
          make install




      - name: Check HTML links with W3C LinkChecker
        continue-on-error: true
        run: |
          checklink -o cli --config .htmltest.yml > htmltest.log || true

      - name: HTML test results
        uses: actions/upload-artifact@v2
        with:
          name: htmltest-report
          path: htmltest.log
          retention-days: 7 # Default is 90 days

      - name: Scan for malware
        run: |
          tools/install-scan.sh
          clamscan -r -i public -l scanlog

      - name: Scan results
        uses: actions/upload-artifact@v2
        with:
          name: clamscan-log
          path: scanlog
          retention-days: 7 # Default is 90 days

      - name: Spell check
        uses: rojopolis/spellcheck-github-actions@0.30.0
        with:
          config_path: .spellcheck.yml
          task_name: Markdown
          output_file: spellcheck-output.txt

      - name: Spelling results
        uses: actions/upload-artifact@v2
        with:
          name: spellcheck-output
          path: spellcheck-output.txt
          retention-days: 7 # Default is 90 days
