name: Deploy Hugo to S3

on:
  workflow_call:
    inputs:
      target:
        description: "Hugo target to deploy to"
        required: true
        type: string
      aws-region:
        description: "AWS Region to use for fetching credentials"
        required: false
        type: string
        default: "us-west-2"
    secrets:
      AWS_OIDC_ROLE:
        required: true
      HUGO_LLM_API:
        required: true
      HUGO_RAG_API:
        required: true
      HUGO_AUDIO_API:
        required: true
      HUGO_PHI_ONNX_LLM_API:
        required: true
      HUGO_DEV_PROG_SIGNIUP_FORM_MUNCHKIN_ID:
        required: true
      HUGO_FORM_ID_FOR_PROGRAM_SIGNUP:
        required: true

env:
  HUGO_VERSION: 0.130.0

jobs:
  build_and_deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-24.04-arm
    permissions:
      id-token: write
      contents: read
    steps:
      # Checks-out the repository under $GITHUB_WORKSPACE, so the job can access it
      - uses: actions/checkout@v4
        with:
          submodules: true # Fetch Hugo Themes
          fetch-depth: 0

      # Sets Up Hugo
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: ${{ env.HUGO_VERSION }}
          extended: true
          
      - name: Clear npm cache
        run: npm cache clean --force
          
      # Installs Post-CSS
      - name: Install Post-CSS
        run: npm install postcss-cli

      - name: AWS Github OIDC Login
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_OIDC_ROLE }}
          aws-region: ${{ inputs.aws-region }}

      # Builds arm-software-developer repo
      - name: Build
        run: |
          hugo --minify
          cp learn-image-sitemap.xml public/learn-image-sitemap.xml
          bin/pagefind.aarch64 --site "public"
        env:
          HUGO_LLM_API: ${{ secrets.HUGO_LLM_API }}
          HUGO_RAG_API: ${{ secrets.HUGO_RAG_API }}
          HUGO_AUDIO_API: ${{ secrets.HUGO_AUDIO_API }}
          HUGO_PHI_ONNX_LLM_API: ${{ secrets.HUGO_PHI_ONNX_LLM_API }}
          HUGO_DEV_PROG_SIGNIUP_FORM_MUNCHKIN_ID: ${{ secrets.HUGO_DEV_PROG_SIGNIUP_FORM_MUNCHKIN_ID }}
          HUGO_FORM_ID_FOR_PROGRAM_SIGNUP: ${{ secrets.HUGO_FORM_ID_FOR_PROGRAM_SIGNUP }}

      # Deploys website to AWS S3 and invalidate CloudFront Cache
      - name: Deploy to S3
        run: hugo deploy --force --maxDeletes -1 --invalidateCDN --target ${{ inputs.target }}
