name: Dispatch Roadmap Update

on:
  pull_request_target:
    types:
      - labeled

jobs:
  call-privileged-update:
    if: |
      github.event.label.name == 'awaiting_tech_review' ||
      github.event.label.name == 'publish'
    runs-on: ubuntu-latest

    steps:
      - name: Check if PROJECT_TOKEN is available
        run: |
          if [ -z "${{ secrets.PROJECT_TOKEN }}" ]; then
            echo "❌ PROJECT_TOKEN is not set or is empty"
            exit 1
          else
            echo "✅ PROJECT_TOKEN is present"
          fi
      - name: Generate and upload PR context
        run: |
          echo "pr_number: ${{ github.event.pull_request.number }}" > pr-context.yml
          echo "label: ${{ github.event.label.name }}" >> pr-context.yml
          echo "repo: ${{ github.repository }}" >> pr-context.yml
      - uses: actions/upload-artifact@v4
        with:
          name: pr-context
          path: pr-context.yml
      - name: Dispatch update-project-dates
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.PROJECT_TOKEN }}
          repository: ArmDeveloperEcosystem/arm-learning-paths
          event-type: update-project-dates
          client-payload: >-
            {
              "pr_number": ${{ github.event.pull_request.number }},
              "label": "${{ github.event.label.name }}",
              "repo": "${{ github.repository }}"
            }