
name: external-links

# Controls when the workflow will run
on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  check-external-links:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11.3

      - name: Check external HTML links
        continue-on-error: true
        run: |
          pip install linkchecker 
          linkchecker --no-robots --config .linkcheckerrc --check-extern https://learn.arm.com/learning-paths/laptops-and-desktops/
          linkchecker --no-robots --config .linkcheckerrc --check-extern https://learn.arm.com/learning-paths/servers-and-cloud-computing/
          linkchecker --no-robots --config .linkcheckerrc --check-extern https://learn.arm.com/learning-paths/mobile-graphics-and-gaming/
          linkchecker --no-robots --config .linkcheckerrc --check-extern https://learn.arm.com/learning-paths/embedded-and-microcontrollers/
          linkchecker --no-robots --config .linkcheckerrc --check-extern https://learn.arm.com/learning-paths/iot/
          linkchecker --no-robots --config .linkcheckerrc --check-extern https://learn.arm.com/learning-paths/automotive/
