name: Generate Monthly Learning Path Report

on:
  workflow_dispatch:

jobs:
  generate-report:
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r tools/requirements.txt

      - name: Generate monthly report
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PAT: ${{ secrets.PAT }}
        run: |
          python tools/generate_monthly_report.py

      - name: Commit and push report to repository
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add reports/
          git commit -m "Add monthly learning path report [skip ci]" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
