name: Assign Reviewer

on:
  pull_request_review_requested:
    types: [review_requested]

jobs:
  assign_reviewer:
    runs-on: ubuntu-latest
    steps:
      - name: Assign Reviewers
        uses: peter-evans/create-pull-request@v3.6.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }} ## Please add the PAT token in the secrets with this name "GITHUB_TOKEN" 
          commit-message: 'Automatically assign reviewer to pull request'
          title: 'Please review my pull request'
          body: 'I would appreciate if you could review my pull request.'
          reviewers: pareena.verma@arm.com,jason.randrews@arm.com
