
name: scan

# Controls when the workflow will run
on:

  # run once a day at 6AM UTC
  schedule:
    - cron: '0 6 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  scan:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          submodules: true  # Fetch Hugo Themes
          fetch-depth: 0 

      # Sets Up Hugo
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
            hugo-version: '0.98.0'
            extended: true
            
      # Builds arm-software-developer repo
      - name: Build
        run: hugo --minify

      # - name: scan
      # run: |
      #   tools/install-scan.sh
      #   clamscan -r -i public -l scanlog
      - name: Install dependencies
        run: sudo apt-get install -y openvas
      - name: Run OpenVAS
        run: sudo openvas-start
      #- name: scan results
      # uses: actions/upload-artifact@v3
      # with:
      #   name: clamscan-log
      #   path: scanlog
      #   retention-days: 7 # Default is 90 days

