name: Open Pull Request with updated stats report
on:
    workflow_run:
      workflows: ["Test Learning Path"]
      types: [completed]
permissions:
  actions: read
  contents: write
  pull-requests: write
jobs:
  stats-pr:
    runs-on: ubuntu-24.04-arm
    steps:
        - name: Checkout main branch
          uses: actions/checkout@v4
          with:
            ref: main
        - name: Download stats report as artifact
          uses: actions/download-artifact@v4
          with:
            # Run ID of the workflow that uploaded the artifact
            run-id: ${{ github.event.workflow_run.id }}
            github-token: ${{ github.token }}
        - name: Check if artifact exists
          run: |
              if [ ! -d stats_current_test_info ]; then
                  echo "No stats artifact found"
                  echo "ARTIFACT_EXIST=false" >> "$GITHUB_ENV"
              else
                  echo "Stats artifact found"
                  echo "ARTIFACT_EXIST=true" >> "$GITHUB_ENV"
              fi
        - name: Move stats file
          # Unpack the artifact and move the stats file to the correct location
          if: env.ARTIFACT_EXIST == 'true'
          run: |
              mv stats_current_test_info/stats_current_test_info.yml data/stats_current_test_info.yml
              rm -rf stats_current_test_info
        - name: Set workflow link as environment variable
          if: env.ARTIFACT_EXIST == 'true'
          run: echo "WORKFLOW_URL=${{ github.event.workflow_run.workflow_url }}" >> $GITHUB_ENV
        - name: Echo Workflow URL
          if: env.ARTIFACT_EXIST == 'true'
          run: echo $WORKFLOW_URL
        - name: Create Pull Request
          uses: peter-evans/create-pull-request@v6
          if: env.ARTIFACT_EXIST == 'true' && success()
          with:
            commit-message: Update stats_current_test_info.yml
            title: Update stats_current_test_info.yml
            body: |
              Update test result file with recent run
              Triggered by workflow run ${ WORKFLOW_URL }
              Auto-generated by create-pull-request: https://github.com/peter-evans/create-pull-request
            branch: update-stats-current-test-info
            base: main
