name: Check Code Quality

on:
  # run once a day at 6AM UTC
  schedule:
    - cron: '0 6 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  check_links:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.98.0'
          extended: true

      - name: Build
        run: hugo --minify

      ## Used w3c-Link checker
      - name: Check w3c-linkchecker links
        continue-on-error: true
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y w3c-linkchecker

      - name: Check links
        run: |
          linkchecker --check-extern --ignore-url=mailto: --no-warnings --no-status -F log -o htmltest.log .htmltest.yml
      
      - name: Upload output file as artifact
        uses: actions/upload-artifact@v2
        with:
          name: w3c-linkchecker-output
          path: htmltest.log
          retention-days: 7 

      - name: Scan for malware
        run: |
          tools/install-scan.sh
          clamscan -r -i public -l scanlog

      - name: Scan results
        uses: actions/upload-artifact@v2
        with:
          name: clamscan-log
          path: scanlog
          retention-days: 7 # Default is 90 days

      - name: Spell check
        uses: rojopolis/spellcheck-github-actions@0.30.0
        with:
          config_path: .spellcheck.yml
          task_name: Markdown
          output_file: spellcheck-output.txt

      - name: Spelling results
        uses: actions/upload-artifact@v2
        with:
          name: spellcheck-output
          path: spellcheck-output.txt
          retention-days: 7 # Default is 90 days
